{{- if .Values.imageCredentials.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.pullSecrets }}
  labels:
    app: {{ template "cfssl-pki.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson" . }}
{{- end }}
