imageCredentials:
  registry: docker.com
  #pullSecrets: docker-registry-secrets
  # username: docker_user
  # password: docker_user_password
# docker image for master and slaves
images:
  master:
    repo: kaarol/jmeter-master
    tag: latest
    pullPolicy: Always
  slave:
    repo: kaarol/jmeter-slave
    tag: latest
    pullPolicy: Always

annotations: {}
config:
  enableSSL: true
  master:
    replicaCount: 1
    restartPolicy: Always
    testType: oneShot
  slaves:
    replicaCount: 2
    restartPolicy: Always
labels: {}
