imageCredentials:
  registry: docker.com
  #pullSecrets: docker-registry-secrets
  # username: docker_user
  # password: docker_user_password
images:
  master:
    repo: kaarol/jmeter-master
    tag: latest
    pullPolicy: Always
  slave:
    repo: kaarol/jmeter-master
    tag: latest
    pullPolicy: Always
